docs/contributing.md, docs/template-project.md
Add documentation describing how to contribute as a person with push access and  a person without push access, also addresses edge case of feature dependent feature via rebasing.
=> Feature contributing

docs/technical-docs/hpc-doc.md
@georgebuzzell I switched to relative path links (and made a little editorial change, which you should feel free to revert!). Let's see if these display correctly on the .io...  If this doesn't work, I have another idea.
=> Fixing image links

README.md
=> Created readme for wiki detailing structure and workflow

_config.yml, docs/technical-docs/hpc-doc.md
Outlined in [hpc-doc](https://github.com/NDCLab/wiki/blob/feature-hpc-farukh/docs/technical-docs/hpc-doc.md)
* [Introduction](#introduction)
* [Connecting to the HPC](#connecting)
* [Establishing VPN Connection](#vpn)
* [Login Node](#login-node)
* [Visual Node](#visual-node)
* [HPC File Structure](#Structure)
* [Git](#git)
* [Singularity](#singularity)
* [Slurm](#slurm)
* [Jupyter](#jupyter)  
Closes #17
=> Created HPC docs

docs/Onboarding/get-with-git.md
@georgebuzzell 
Two minor tweaks based on initial testing feedback from Arina, as well as addition of the demo video where I add my content to the who's-who page.  Please merge so that the video will be available to round 1 testers when they hit that point.  Thanks!
=> Improve get-with-git

docs/around-the-lab/roles-expectations.md
@georgebuzzell
Please check suggested edits to include lab dress code.
=> Add dress code

README.md
- removed branching illustration and requirement to create sub-branches
=> Updated README to reflect new branching principle

docs/Onboarding/slack-setup.md
Hi @jessb0t ! I made a change to one of the pages on the wiki as my improvement for the last step of the Get with Git 😄
=> Improvement on Wiki from Sarah

docs/around-the-lab/taking-time.md
Hey @jessb0t this is my improvement. I removed the word "and" from one of the bullets under the taking time away section.
=> Feature removeandfromtakingtime ana

.gitignore, Gemfile, README.md, _config.yml
- included gemfile
- reduced steps to init website
- placed "jemoji" under plugins
=> integrate gem packages

docs/Onboarding/get-with-git.md
@emach039 Please review my suggested change here. 🤓  If it looks good to you, you will need to leave your comment(s) in the "Review changes" box (top right of the PR window) and select the "Approve" radio button.  This will unlock it so that the branch can be merged to main.  Then you can click the Merge button at the bottom and commit the merge!  Thank you!
=> Clarify hands-on training

docs/technical-docs/git_and_github.md
@apoly1 Please review my pull request. 🤓 If it looks good to you, you will need to leave your comment(s) in the "Review changes" box (top right of the PR window) and select the "Approve" radio button. This will unlock it so that the branch can be merged to main. Then you can click the Merge button at the bottom and commit the merge! Thank you!
=> Add notifications info

docs/etiquette/github-etiquette.md, docs/etiquette/github-templates.md, docs/etiquette/naming-conventions.md
@georgebuzzell I tweaked two pages on the wiki to add notes about the new template repos.  I also added notes about correcting data, which goes hand-in-hand with more specific instructions embedded in the template-dataset readme files.
=> Update with details for dataset/analysis templates

docs/technical-docs/git_and_github.md, docs/technical-docs/shell.md
Hey @jessb0t 🙂 Let's see if I got it right this time 😅 
I added that everyone should make sure to be within their root when they create a directory, however, I'm not sure which command they should use in case they are not. Would you mind adding that or let me know which command I should write?
=> Fixed old issues and added mkdir

docs/technical-docs/git_and_github.md, docs/technical-docs/shell.md
Hi @jessb0t 🙂 Please check this pull request, I added the mkdir command to the list of shell commands
=> Add mkdir to shell commands

docs/current-projects/rwe-alpha.md, docs/technical-docs/docker-usage.md, docs/technical-docs/pavlovia.md, docs/technical-docs/python-ci-workflow.md, docs/technical-docs/zotero.md
@anaNDClab tagging you here so you can review (since you are the other senior RA for the project) 🙂 
Tagging you as well @jessb0t just to make sure I am creating a pull request to the correct branch (dev-rwe) 🙂
=> Git a thon rwe sarah

docs/current-projects/social-context-alpha.md
I finish the main question for the Current Projects page @emach039.
=> social-context-alpha.md

docs/technical-docs/git_and_github.md
@jessb0t  Finally put it on the wiki! I opted to not include the Markdown elements because I felt like the external links in the Markdown section covered what I had covered, plus much more.
If you have any suggestions on what I could add to make the arrangement of the tables less awkward(?), feel free to annotate.
=> Cheat sheet

docs/etiquette/programming-standards.md, docs/technical-docs/git_and_github.md, docs/technical-docs/hpc-doc.md
Hey @jessb0t please review my changes to the programming standards page, the git + github page, and the hpc page. Thank you.
I made the following changes: 
- I changed the sizes of the headers 
- I added the work "contents" to mark the top section of the pages 
- I added subheadings that were missing to the hpc page 
- I added the subheadings into the contents section for some of the pages 
- I changed the bullets in the content section into numbers 
I have one question. Some pages after the content section have an introduction section while others have an overview section. Should all the pages be changed to say introduction instead of overview after the contents section?
=> Add ana's changes to the wiki

docs/technical-docs/docker-usage.md, docs/technical-docs/git_and_github.md, docs/technical-docs/hpc-doc.md, docs/technical-docs/pavlovia.md, docs/technical-docs/python-ci-workflow.md, docs/technical-docs/shell.md, docs/technical-docs/zenhub.md, docs/technical-docs/zotero.md
@jessb0t 'beautified' shell and zotero pages, updated nav order for all pages. Please let me know if I missed anything!
=> Beautify markdown alycia

docs/technical-docs/zotero.md
=> Added caveats

.github/pull_request_template/main-merge_template.md
@georgebuzzell @F-said 
Third of three PRs heading your way to add pull request templates!  I have also opened #158 to push these templates into our existing set of repos, once reviewed and approved.  We can discuss details next Tuesday.
=> Add pull request template

docs/Onboarding/get-with-git.md
Hi again! Per the end of the video, I wanted to try and see if I could contribute to the wiki. I decided to go back to change one minor discrepancy I had noticed between the video and the written instructions regarding which files needed to be modified or added. (Minor, but I had been following along on the written part alone and had to stop and go back to watch the video since this part left me unsure as to whether I would be adding and committing the right files.) Feel free to merge if you think it could tabe useful to anyone else, but you can totally ignore this if I'm meddling with something intended!!
=> Update written git instructions to match video

docs/technical-docs/zotero.md
**Zotero**: added new section on how to check for duplicates
@ostibolt Here is a quick update to the Zotero page to handle George's concern today about checking for duplicates after adding papers.  Please let me know what you think! :pray:
=> Add instructions for handling duplicates

docs/etiquette/naming-conventions.md
**Naming Conventions**: added naming option for zipped digi file
=> Add zipped digi option

docs/hpc/jobs.md
**HPC>Jobs**: added line to load singularity (was missing) and included it in the explanatory table.
@davhunt Let me know if you have any questions!
=> Add singularity load

Gemfile
=> specify gem versions

docs/etiquette/data-monitoring.md
=> update data monitoring page

Gemfile, _sass/buttons.scss
=> Buttons fix

docs/hpc/jobs.md
=> add info for submitting highmem jobs

docs/around-the-lab/roles-expectations.md
HI Lilly! I updated the rules and expectations page on the wiki. Please review it whenever you can. @lillylaplace
=> added hyperlink to PSY4940 page

docs/hpc/R.md, docs/hpc/matlab.md, docs/hpc/python.md
=> update documentation for running Python or R scripts with HPC modules
